services:
  api:
    build: .
    image: talonr:latest
    command: ["npm", "run", "start"]
    env_file:
      - ../.env
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    restart: unless-stopped

  worker:
    image: talonr:latest
    depends_on:
      - api
    command: ["npm", "run", "start:worker"]
    env_file:
      - ../.env
    environment:
      NODE_ENV: production
    shm_size: "1gb"
    restart: unless-stopped
